n = input("Digite algo: ")
print('O valor primitivo desse valor é ', type(n))
print('Tem espaços? ', n.isspace())
print('É numérico? ', n.isnumeric())
print('É alfabético? ', n.isalpha())
print('É alfanumérico? ', n.isalnum())
print('Está em maiúscula? ', n.isupper())
print('Está em minúscula? ', n.islower())
print('Está capitalizada? ', n.istitle())
